import Head from "next/head";
import { Layout } from "../components/Layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center min-h-screen text-white bg-black">
        <div className="absolute w-2/3 mr-4 rounded-full opacity-10 bg-primary-200 dark:bg-primary-900 dark:opacity-50 h-80 light:mix-blend-multiply filter blur-3xl animate-blob" />
        <div className="w-full max-w-2xl px-4">
          <Layout />
        </div>
      </main>
    </>
  );
}
